#git_username:
#git_credential:
registry_password: env
registry_namespace: container-registry
challenge_namespace: challenges
istio_namespace: istio-system
tcp_domain_name: localhost
https_domain_name: localhost
certificate_issuer_name: istio-issuer
istio_ingress_name: ingressgateway
external_tcp_port: 443
external_https_port: 443
expire_interval: 3600
ctfd_url: http://192.168.2.24:8000
